### ISSUE TITLE
[BP-BUG] packet spam incorrectly triggering

### ISSUE THREAD

**Issue by thisRandomm** [PointLife/PointLife-Issues#12]
**Describe the bug**
If you surrender, and hold LMB it will kick you for packet spam

**To Reproduce**
Above

**Expected behavior**
Not getting kicked

**Comment by thisRandomm** [comment]
It also does that when someone is cuffed, and mounted by someone

**Comment by NongBenz** [comment]
Thanks for report, both cases fixed for next patch.
