### ISSUE TITLE
[BP-BUG] Disconnect while in apartment, that is in interiour, spawn in water after reconnect

### ISSUE THREAD

**Issue by PLASMAchicken** [PointLife/PointLife-Issues#23]
**Describe the bug**
When getting reconnected in apartment, which door is in an interior, you spawn in the water after reconnecting.

**To Reproduce**
1. Go into IHT
2. Go into Apartment
3. Get Reconnected to Server by Restart or Crash
4. Spawn in Water

**Expected behavior**
Not spawn in water

**Comment by NongBenz** [comment]
Oh yeah IHT does have that interior setup I didn't think about when writing this. This looks like it should fix it, nice catch! You and Unishark will be credited as developers coming on 1.38, thanks for your work. Will catch up on Discord soon.

**Comment by NongBenz** [comment]
Just realized I commented on the PL repo and not BP PR, skill issue
