### ISSUE TITLE
[BP-BUG] Lockpicking(CrackStart) works on every Entity

### ISSUE THREAD

**Issue by PLASMAchicken** [PointLife/PointLife-Issues#24]
Describe the bug
CrackStart can be used on every Entity

To Reproduce
Use modified Client to enable Crack option permanently
Crack any Entity, like a Door or Player, after minigame you can search their whole inventory
Rob Player by using 1 Lockpick instead of needing to Cuff them.

Expected behavior
A player cannot be cracked and robbed of his belongings.

**Comment by NongBenz** [comment]
Good find, fixed in LifeSource for beta 2
https://github.com/broke-protocol/broke-protocol/commit/08ee69cd6a8c099a70eab5ac9adb1293e28ea36d
