### ISSUE TITLE
[BP-BUG] Warn panel in-game a bit broken.

### ISSUE THREAD

**Issue by Qcoomber** [PointLife/PointLife-Issues#3]
**Describe the bug**
When using the warn panel in-game only the in-game/warns will be updated but the profile in Discord will not be updated. Only after another warn using the full command (/warn {Username} {Reason}) will the profile in discord get updated with both warnings. If however another warning is issued using the panel only the previous warn before the present will be updated.

**To Reproduce**
1. Go in-game, type /warn username and choose a warn in the panel. I'll choose RDM as an example.
2. The warn in-game will be updated in the /warns BUT the warn in discord "!info" profile will not appear.
3. Next, Go in-game again and type /warn username and choose a warn in the panel. I'll use RDA as an example.
4. Both of the warns will appear in /warns BUT in discord only the previous warn (RDM) will appear not the RDA warn.

**Expected behavior**
I expect the warn to be updated both in-game and in Discord eliminating the possibility of misunderstanding in staff's judgement.

**Screenshots**
I can add some screenshots/a video if my description is still confusing.

**Additional context**
Laggernoob and several other staff have been experiencing problems where their warn just won't register when they use the command !info in Discord. They then decided to report it to me which led me here.

**Comment by PLASMAchicken** [comment]
Try /warn <name> but dont select anything. This should also update the Warns.
Beacause currently PPC gets warns sent when /warn or /removewarn is after 1s, but with the panel the warn gets added long after command has been run.

Will add a patch to BPE AddWarn Methode.

**Comment by Qcoomber** [comment]
@PLASMAchicken Just found out that warns are not updated in Risk info moderation.
![asd](https://github.com/PointLife/PointLife-Issues/assets/143277984/57579122-f28c-4890-a93a-051b3256f18c)
![asdf](https://github.com/PointLife/PointLife-Issues/assets/143277984/b34d1b21-65ec-43aa-8369-3b526b607505)

**Comment by PLASMAchicken** [comment]
Did you check the latest generation date?
