### ISSUE TITLE
[BP-BUG] [SEC3] Vaults respawn money when placed in Cloned Apartment

### ISSUE THREAD

**Issue by PLASMAchicken** [PointLife/PointLife-Issues#44]
Thanks pauloo for reporting
Related to #37 #42 
Vaults when placed in cloned apartment without Place#owner are placed with 10k...

`SvEntity#Initialize` seems to still be using `Place#owner` instead of `Place#IsClone`

**Comment by PLASMAchicken** [comment]
@nongbenz Latests Scripts.dll from Steam seems to still have this issue

**Comment by NongBenz** [comment]
Thanks, fixed now for next release/hotfix
